// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXSR-AoNncN5aobl34sJmWM53Z4O9DDGk',
    appId: '1:892771060976:web:52c3cac1984850923b0635',
    messagingSenderId: '892771060976',
    projectId: 'shop-d9e74',
    authDomain: 'shop-d9e74.firebaseapp.com',
    databaseURL: 'https://shop-d9e74-default-rtdb.firebaseio.com',
    storageBucket: 'shop-d9e74.appspot.com',
    measurementId: 'G-01ZQYQX1XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK-c8hk59KZ5R7GS9EgwNrkapzU9E0lyc',
    appId: '1:892771060976:android:2945032747f3817f3b0635',
    messagingSenderId: '892771060976',
    projectId: 'shop-d9e74',
    databaseURL: 'https://shop-d9e74-default-rtdb.firebaseio.com',
    storageBucket: 'shop-d9e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGu5Ut6HAFemom8iLbuX9YZxkl-01sck',
    appId: '1:892771060976:ios:897817ce258b168d3b0635',
    messagingSenderId: '892771060976',
    projectId: 'shop-d9e74',
    databaseURL: 'https://shop-d9e74-default-rtdb.firebaseio.com',
    storageBucket: 'shop-d9e74.appspot.com',
    iosClientId: '892771060976-1hqs8leih2dg9u179tarhqaelapam8cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGu5Ut6HAFemom8iLbuX9YZxkl-01sck',
    appId: '1:892771060976:ios:5de6c3230c00b43a3b0635',
    messagingSenderId: '892771060976',
    projectId: 'shop-d9e74',
    databaseURL: 'https://shop-d9e74-default-rtdb.firebaseio.com',
    storageBucket: 'shop-d9e74.appspot.com',
    iosClientId: '892771060976-552qp5s3dmloa421v4mshgh67cf4jvni.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopflex.RunnerTests',
  );
}
